#!/bin/bash
set -e
_SAVED_VARIABLE=__CONDA_SHLVL_${CONDA_SHLVL}_HDF5_PLUGIN_PATH
[ -v $_SAVED_VARIABLE ] && {
  eval HDF5_PLUGIN_PATH=\$$_SAVED_VARIABLE
  export HDF5_PLUGIN_PATH
  unset __CONDA_SHLVL_${CONDA_SHLVL}_HDF5_PLUGIN_PATH
} || unset HDF5_PLUGIN_PATH
unset _SAVED_VARIABLE
